openapi: 3.0.0
info:
  title: Auth API
  description: 認証API
  termsOfService: https://auth.lvnmatch.com/
  version: 1.0.0
paths:
  /login/:
    post:
      tags:
        - Login
      summary: Login with email & password
      parameters:
        - in: query
          name: client
          description: if selfplan, must be selfplan
          required: false
          schema:
            type: string
          allowReserved: true
      requestBody:
        description: email and password
        required: true
        content:
          application/json:
            schema:
              example:
                email: example@example.com
                password: aaaaaaaa
      responses:
        '200':
          $ref: '#components/responses/LoginSuccessApp'
  /login/web/:
    post:
      tags:
        - Login
      summary: Login with email & password
      requestBody:
        description: email and password
        required: true
        content:
          application/json:
            schema:
              example:
                email: example@example.com
                password: aaaaaaaa
      responses:
        '200':
          $ref: '#components/responses/LoginSuccess'
  /login/auto/:
    post:
      tags:
        - Auto Login
      summary: Auto login for appli (by secure storage)
      requestBody:
        description: idToken and refreshToken
        required: true
        content:
          application/json:
            schema:
              example:
                idToken: adlkewie.ajdaweelke.akldfjla
                refreshToken: klasdjwaeoi.dkljaewi.kldjl
      responses:
        '200':
          $ref: '#components/responses/LoginSuccessApp'
  /login/auto/web/:
    get:
      tags:
        - Auto Login
      summary: Auto login for web (by cookie)
      parameters:
        - in: cookie
          name: accessToken
          schema:
            type: string
        - in: cookie
          name: refreshToken
          schema:
            type: string
      responses:
        '200':
          $ref: '#components/responses/LoginSuccess'
  /refresh/:
    post:
      tags:
        - Refresh(SSR)
      summary: Refresh token in cookie. This is for SSR(Next).
      requestBody:
        description: accessToken and refreshToken
        required: true
        content:
          application/json:
            schema:
              example:
                idToken: adlkewie.ajdaweelke.akldfjla
                refreshToken: klasdjwaeoi.dkljaewi.kldjl
      responses:
        '200':
          $ref: '#components/responses/LoginSuccessApp'
  /logout/:
    get:
      tags:
        - Logout
      summary: Logout and delete cookie
      responses:
        '200':
          description: success
          headers:
            Delete-Cookie:
              schema:
                type: array
                example:
                  - accessToken
                  - refreshToken
components:
  responses:
    LoginSuccess:
      description: success
      headers:
        Set-Cookie:
          schema:
            type: array
            example:
              - accessToken=jasjewiewijfejesa.salkdliawej.laslk
              - refreshToken=ajkljfwaeioeje.jasliwoeafae.jasifjaweiojei
      content:
        application/json:
          schema:
            type: array
            example:
              user: 
                id: 10000
                email: example@example.com
                name: foo bar
                customer_id: cs11
                customer_name: 剛田不動産
                consultant_id: 9
                consultant_name: 鈴木イチロー
                consultant_dept: セーフコオフィス
                consultant_email: ichiro@example.com
                consultant_phone: 09000000000
                site_codes:
                  - sf
                  - kz
                acl: 12
                parent_id: null
                children:
                  - ikkyu
                group_id:
                  - 10
                  - 20
                contract_type: 1
                shutout_flag: 0
                status: a
                selfplan_progress: null
    LoginSuccessApp:
      description: success (appli)
      content:
        application/json:
          schema:
            type: array
            example:
              idToken: jasjewiewijfejesa.salkdliawej.laslk
              refreshToken: ajkljfwaeioeje.jasliwoeafae.jasifjaweiojei
              user: 
                id: 10000
                email: example@example.com
                name: foo bar
                customer_id: cs11
                customer_name: 剛田不動産
                consultant_id: 9
                consultant_name: 鈴木イチロー
                consultant_dept: セーフコオフィス
                consultant_email: ichiro@example.com
                consultant_phone: 09000000000
                site_codes:
                  - sf
                  - kz
                acl: 12
                parent_id: null
                children:
                  - ikkyu
                group_id:
                  - 10
                  - 20
                contract_type: 1
                shutout_flag: 0
                status: a
                selfplan_progress: null
  schemas:
    User:
      type: "object"
      properties:
        id: 
          type: integer
        email:
          type: string
        name:
          type: string
        customer_id:
          type: string
        customer_name:
          type: string
        consultant_id:
          type: integer
        consultant_name:
          type: string
        consultant_dept:
          type: string
        consultant_email:
          type: string
        consultant_phone:
          type: string
        site_codes:
          type: array
        acl:
          type: integer
        parent_id:
          type: integer
        children:
          type: array
        group_id:
          type: array
        contract_type:
          type: integer
        shutout_flag:
          type: integer
        status:
          type: string
        selfplan_progress:
          type: integer
  # securitySchemes:
  #   idToken:
  #     type: apiKey
  #     in: cookie
  #     name: accessToken
  #   refreshToken:
  #     type: apiKey
  #     in: cookie
  #     name: refreshToken
  